name: Rust

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install stable rust release
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.46.0
          override: true
          components: rustfmt, clippy

      - name: Check source formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: clippy
      #        args: -- -D warnings

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
